package eu.gpapadop.netwatchpro.enums.permissions_danger;

public enum HighRiskPermissions {
    ACCESS_BACKGROUND_LOCATION("ACCESS_BACKGROUND_LOCATION", 4),
    ACCESS_COARSE_LOCATION("ACCESS_COARSE_LOCATION", 4),
    ACCESS_FINE_LOCATION("ACCESS_FINE_LOCATION", 4),
    ACTIVITY_RECOGNITION("ACTIVITY_RECOGNITION", 4),
    ANSWER_PHONE_CALLS("ANSWER_PHONE_CALLS", 4),
    BIND_ACCESSIBILITY_SERVICE("BIND_ACCESSIBILITY_SERVICE", 4),
    BIND_APPWIDGET("BIND_APPWIDGET", 4),
    BIND_AUTOFILL_SERVICE("BIND_AUTOFILL_SERVICE", 4),
    BIND_CARRIER_MESSAGING_CLIENT_SERVICE("BIND_CARRIER_MESSAGING_CLIENT_SERVICE", 4),
    BIND_CARRIER_MESSAGING_SERVICE("BIND_CARRIER_MESSAGING_SERVICE", 4),
    BIND_CARRIER_SERVICES("BIND_CARRIER_SERVICES", 4),
    BIND_CHOOSER_TARGET_SERVICE("BIND_CHOOSER_TARGET_SERVICE", 4),
    BIND_CONTROLS("BIND_CONTROLS", 4),
    BIND_DREAM_SERVICE("BIND_DREAM_SERVICE", 4),
    BIND_INCALL_SERVICE("BIND_INCALL_SERVICE", 4),
    BIND_INPUT_METHOD("BIND_INPUT_METHOD", 4),
    BIND_MIDI_DEVICE_SERVICE("BIND_MIDI_DEVICE_SERVICE", 4),
    BIND_NFC_SERVICE("BIND_NFC_SERVICE", 4),
    BIND_NOTIFICATION_LISTENER_SERVICE("BIND_NOTIFICATION_LISTENER_SERVICE", 4),
    BIND_PRINT_SERVICE("BIND_PRINT_SERVICE", 4),
    BIND_QUICK_ACCESS_WALLET_SERVICE("BIND_QUICK_ACCESS_WALLET_SERVICE", 4),
    BIND_QUICK_SETTINGS_TILE("BIND_QUICK_SETTINGS_TILE", 4),
    BIND_REMOTEVIEWS("BIND_REMOTEVIEWS", 4),
    BIND_SCREENING_SERVICE("BIND_SCREENING_SERVICE", 4),
    BIND_TELECOM_CONNECTION_SERVICE("BIND_TELECOM_CONNECTION_SERVICE", 4),
    BIND_TEXT_SERVICE("BIND_TEXT_SERVICE", 4),
    BIND_TV_INPUT("BIND_TV_INPUT", 4),
    BIND_VISUAL_VOICEMAIL_SERVICE("BIND_VISUAL_VOICEMAIL_SERVICE", 4),
    BIND_VOICE_INTERACTION("BIND_VOICE_INTERACTION", 4),
    BIND_VPN_SERVICE("BIND_VPN_SERVICE", 4),
    BIND_VR_LISTENER_SERVICE("BIND_VR_LISTENER_SERVICE", 4),
    BIND_WALLPAPER("BIND_WALLPAPER", 4),
    INTERNET("INTERNET", 4),
    NFC_PREFERRED_PAYMENT_INFO("NFC_PREFERRED_PAYMENT_INFO", 4),
    NFC_TRANSACTION_EVENT("NFC_TRANSACTION_EVENT", 4),
    PROCESS_OUTGOING_CALLS("PROCESS_OUTGOING_CALLS", 4),
    RECEIVE_MMS("RECEIVE_MMS", 4),
    RECEIVE_SMS("RECEIVE_SMS", 4),
    RECEIVE_WAP_PUSH("RECEIVE_WAP_PUSH", 4),
    SEND_RESPOND_VIA_MESSAGE("SEND_RESPOND_VIA_MESSAGE", 4),
    USE_BIOMETRIC("USE_BIOMETRIC", 4),
    USE_FINGERPRINT("USE_FINGERPRINT", 4),
    USE_FULL_SCREEN_INTENT("USE_FULL_SCREEN_INTENT", 4),
    USE_SIP("USE_SIP", 4),
    WRITE_CALENDAR("WRITE_CALENDAR", 4),
    WRITE_SYNC_SETTINGS("WRITE_SYNC_SETTINGS", 4);

    private String permissionName;
    private int permissionPoints;

    HighRiskPermissions(String newPermissionName, int newPermissionPoints){
        this.permissionName = "android.permission." + newPermissionName;
        this.permissionPoints = newPermissionPoints;
    }

    public String getPermissionName(){
        return this.permissionName;
    }

    public int getPermissionPoints(){
        return this.permissionPoints;
    }
}
