package eu.gpapadop.netwatchpro.enums.permissions_danger;

public enum ModerateRiskPermissions {
    ACCESS_CHECKIN_PROPERTIES("ACCESS_CHECKIN_PROPERTIES", 3),
    ACCESS_LOCATION_EXTRA_COMMANDS("ACCESS_LOCATION_EXTRA_COMMANDS", 3),
    ACCESS_MEDIA_LOCATION("ACCESS_MEDIA_LOCATION", 3),
    ACCESS_NETWORK_STATE("ACCESS_NETWORK_STATE", 3),
    ACCESS_NOTIFICATION_POLICY("ACCESS_NOTIFICATION_POLICY", 3),
    ACCESS_WIFI_STATE("ACCESS_WIFI_STATE", 3),
    ACCOUNT_MANAGER("ACCOUNT_MANAGER", 3),
    ADD_VOICEMAIL("ADD_VOICEMAIL", 3),
    BATTERY_STATS("BATTERY_STATS", 3),
    BIND_CALL_REDIRECTION_SERVICE("BIND_CALL_REDIRECTION_SERVICE", 3),
    BLUETOOTH("BLUETOOTH", 3),
    BLUETOOTH_ADMIN("BLUETOOTH_ADMIN", 3),
    BLUETOOTH_PRIVILEGED("BLUETOOTH_PRIVILEGED", 3),
    BODY_SENSORS("BODY_SENSORS", 3),
    BROADCAST_PACKAGE_REMOVED("BROADCAST_PACKAGE_REMOVED", 3),
    BROADCAST_SMS("BROADCAST_SMS", 3),
    BROADCAST_STICKY("BROADCAST_STICKY", 3),
    BROADCAST_WAP_PUSH("BROADCAST_WAP_PUSH", 3),
    CALL_COMPANION_APP("CALL_COMPANION_APP", 3),
    CALL_PRIVILEGED("CALL_PRIVILEGED", 3),
    CHANGE_COMPONENT_ENABLED_STATE("CHANGE_COMPONENT_ENABLED_STATE", 3),
    CHANGE_CONFIGURATION("CHANGE_CONFIGURATION", 3),
    CHANGE_NETWORK_STATE("CHANGE_NETWORK_STATE", 3),
    CHANGE_WIFI_MULTICAST_STATE("CHANGE_WIFI_MULTICAST_STATE", 3),
    CHANGE_WIFI_STATE("CHANGE_WIFI_STATE", 3),
    CLEAR_APP_CACHE("CLEAR_APP_CACHE", 3),
    CONTROL_LOCATION_UPDATES("CONTROL_LOCATION_UPDATES", 3),
    DELETE_CACHE_FILES("DELETE_CACHE_FILES", 3),
    DIAGNOSTIC("DIAGNOSTIC", 3),
    DISABLE_KEYGUARD("DISABLE_KEYGUARD", 3),
    DUMP("DUMP", 3),
    EXPAND_STATUS_BAR("EXPAND_STATUS_BAR", 3),
    FACTORY_TEST("FACTORY_TEST", 3),
    FOREGROUND_SERVICE("FOREGROUND_SERVICE", 3),
    GET_ACCOUNTS("GET_ACCOUNTS", 3),
    GET_ACCOUNTS_PRIVILEGED("GET_ACCOUNTS_PRIVILEGED", 3),
    GET_PACKAGE_SIZE("GET_PACKAGE_SIZE", 3),
    GET_TASKS("GET_TASKS", 3),
    GLOBAL_SEARCH("GLOBAL_SEARCH", 3),
    INSTALL_LOCATION_PROVIDER("INSTALL_LOCATION_PROVIDER", 3),
    INSTALL_SHORTCUT("INSTALL_SHORTCUT", 3),
    INSTANT_APP_FOREGROUND_SERVICE("INSTANT_APP_FOREGROUND_SERVICE", 3),
    INTERACT_ACROSS_PROFILES("INTERACT_ACROSS_PROFILES", 3),
    KILL_BACKGROUND_PROCESSES("KILL_BACKGROUND_PROCESSES", 3),
    LOADER_USAGE_STATS("LOADER_USAGE_STATS", 3),
    LOCATION_HARDWARE("LOCATION_HARDWARE", 3),
    MANAGE_DOCUMENTS("MANAGE_DOCUMENTS", 3),
    MANAGE_EXTERNAL_STORAGE("MANAGE_EXTERNAL_STORAGE", 3),
    MANAGE_OWN_CALLS("MANAGE_OWN_CALLS", 3),
    MASTER_CLEAR("MASTER_CLEAR", 3),
    MEDIA_CONTENT_CONTROL("MEDIA_CONTENT_CONTROL", 3),
    MODIFY_AUDIO_SETTINGS("MODIFY_AUDIO_SETTINGS", 3),
    MOUNT_FORMAT_FILESYSTEMS("MOUNT_FORMAT_FILESYSTEMS", 3),
    MOUNT_UNMOUNT_FILESYSTEMS("MOUNT_UNMOUNT_FILESYSTEMS", 3),
    PACKAGE_USAGE_STATS("PACKAGE_USAGE_STATS", 3),
    PERSISTENT_ACTIVITY("PERSISTENT_ACTIVITY", 3),
    QUERY_ALL_PACKAGES("QUERY_ALL_PACKAGES", 3),
    READ_CALENDAR("READ_CALENDAR", 3),
    READ_CALL_LOG("READ_CALL_LOG", 3),
    READ_CONTACTS("READ_CONTACTS", 3),
    READ_EXTERNAL_STORAGE("READ_EXTERNAL_STORAGE", 3),
    READ_INPUT_STATE("READ_INPUT_STATE", 3),
    READ_LOGS("READ_LOGS", 3),
    READ_PHONE_NUMBERS("READ_PHONE_NUMBERS", 3),
    READ_PHONE_STATE("READ_PHONE_STATE", 3),
    READ_PRECISE_PHONE_STATE("READ_PRECISE_PHONE_STATE", 3),
    READ_SMS("READ_SMS", 3),
    READ_SYNC_SETTINGS("READ_SYNC_SETTINGS", 3),
    READ_SYNC_STATS("READ_SYNC_STATS", 3),
    READ_VOICEMAIL("READ_VOICEMAIL", 3),
    REBOOT("REBOOT", 3),
    RECEIVE_BOOT_COMPLETED("RECEIVE_BOOT_COMPLETED", 3),
    RESTART_PACKAGES("RESTART_PACKAGES", 3),
    SET_ALARM("SET_ALARM", 3),
    SET_PREFERRED_APPLICATIONS("SET_PREFERRED_APPLICATIONS", 3),
    SET_WALLPAPER("SET_WALLPAPER", 3),
    SET_WALLPAPER_HINTS("SET_WALLPAPER_HINTS", 3),
    SIGNAL_PERSISTENT_PROCESSES("SIGNAL_PERSISTENT_PROCESSES", 3),
    START_VIEW_PERMISSION_USAGE("START_VIEW_PERMISSION_USAGE", 3),
    STATUS_BAR("STATUS_BAR", 3),
    TRANSMIT_IR("TRANSMIT_IR", 3),
    UNINSTALL_SHORTCUT("UNINSTALL_SHORTCUT", 3),
    UPDATE_DEVICE_STATS("UPDATE_DEVICE_STATS", 3),
    WAKE_LOCK("WAKE_LOCK", 3);

    private String permissionName;
    private int permissionPoints;

    ModerateRiskPermissions(String newPermissionName, int newPermissionPoints){
        this.permissionName = "android.permission." + newPermissionName;
        this.permissionPoints = newPermissionPoints;
    }

    public String getPermissionName(){
        return this.permissionName;
    }

    public int getPermissionPoints(){
        return this.permissionPoints;
    }
}
